minimum_pre_commit_version: "3.6.0"

repos:
  # Pinned wheel from PyPI – no Git clone, no tag problems
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

  # keep flake8 (example)
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: lint-js
        name: lint js
        entry: npm run lint:js
        language: system
        pass_filenames: false
      - id: format-js
        name: format js write
        entry: npm run format:js:write
        language: system
        pass_filenames: false
      - id: lint-css
        name: lint css
        entry: npm run lint:css
        language: system
        pass_filenames: false
