[mypy]
python_version = 3.12
files = app, scripts
cache_dir = .mypy_cache
ignore_missing_imports = True
warn_unused_ignores = True
show_error_codes = True

# Uncomment module-by-module after cleanup
# disallow_untyped_defs = True
# disallow_incomplete_defs = True

[mypy-tests.*]
ignore_errors = True

# Plugins
plugins = sqlmypy
