"""Curated list of publicly accessible camera feeds."""

INTERNET_CAMERAS = [
    # Clocks / Time References
    {
        "id": "time-nist-clock",
        "name": "NIST Official US Time",
        "url": "https://time.gov/widget/embedNISTwidget.html",
        "refresh_sec": 30,
        "category": "clock",
        "notes": "JS-rendered; still image after page load is fine for Glimpser.",
    },
    {
        "id": "usno-master-clock",
        "name": "US Naval Observatory Master Clock",
        "url": "https://www.usno.navy.mil/apps/clock.html",
        "refresh_sec": 30,
        "category": "clock",
    },
    {
        "id": "ptb-braunschweig-clock",
        "name": "PTB Braunschweig Atomic Clock (DE)",
        "url": "https://uhr.ptb.de/time_ptb.png",
        "refresh_sec": 60,
        "category": "clock",
    },
    {
        "id": "timeanddate-utc",
        "name": "TimeAndDate UTC Digital Clock",
        "url": "https://free.timeanddate.com/clock/i8zbmyr0/n1440/szw160/szh160/hbw0/hfcfff/cf100/hncfff/mqcfff/mbw0/mhcfff/pt3",
        "refresh_sec": 60,
        "category": "clock",
    },
    # NOAA / Geostationary Satellites
    {
        "id": "goes-east-geocolor-fd",
        "name": "GOES-East Full Disk (GeoColor)",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/latest.jpg",
        "refresh_sec": 600,
        "category": "satellite",
        "notes": "≈18 MP JPG; updates every 10 min.",
    },
    {
        "id": "goes-west-geocolor-fd",
        "name": "GOES-West Full Disk (GeoColor)",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES18/ABI/FD/GEOCOLOR/latest.jpg",
        "refresh_sec": 600,
        "category": "satellite",
    },
    {
        "id": "goes-east-conus-geocolor",
        "name": "GOES-East CONUS GeoColor",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/CONUS/GEOCOLOR/latest.jpg",
        "refresh_sec": 300,
        "category": "satellite",
    },
    {
        "id": "goes-west-conus-geocolor",
        "name": "GOES-West CONUS GeoColor",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES18/ABI/CONUS/GEOCOLOR/latest.jpg",
        "refresh_sec": 300,
        "category": "satellite",
    },
    {
        "id": "goes-east-band07",
        "name": "GOES-East Band 7 (SWIR)",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/07/latest.jpg",
        "refresh_sec": 600,
        "category": "satellite",
    },
    {
        "id": "goes-west-band13",
        "name": "GOES-West Band 13 (IR)",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES18/ABI/FD/13/latest.jpg",
        "refresh_sec": 600,
        "category": "satellite",
    },
    {
        "id": "himawari-8-geocolor-fd",
        "name": "Himawari-9 Full Disk (GeoColor)",
        "url": "https://himawari8.nict.go.jp/img/D531106/2d/550/latest.png",
        "refresh_sec": 600,
        "category": "satellite",
    },
    {
        "id": "meteosat-11-vis",
        "name": "Meteosat-11 Full Disk (VIS 0.6 µm)",
        "url": "https://oiswww.eumetsat.org/IPPS/html/latestImages/EUMETSAT_MSG_VIS006_color.jpg",
        "refresh_sec": 900,
        "category": "satellite",
    },
    {
        "id": "meteosat-9-indian-ocean",
        "name": "Meteosat-9 Indian Ocean Service RGB",
        "url": "https://www.eumetsat.int/website/wcm/idc/idcplg?IdcService=GET_FILE&dDocName=IMAGE_MET9_FD&allowInterrupt=1",
        "refresh_sec": 900,
        "category": "satellite",
    },
    {
        "id": "goes-east-glm",
        "name": "GOES-East GLM Flash Density",
        "url": "https://cdn.star.nesdis.noaa.gov/GOES16/GLM/FD/GOES16-GLM_FD_Flash_Density/latest.png",
        "refresh_sec": 300,
        "category": "satellite",
    },
    {
        "id": "jp-mtsat-japan-fd",
        "name": "JMA Himawari-9 Japan RGB",
        "url": "https://www.data.jma.go.jp/mscweb/data/himawari/img/fld/FD/allband/002/20230701/latest.png",
        "refresh_sec": 600,
        "category": "satellite",
    },
    # Solar & Space-Weather Plots
    {
        "id": "sdo-aia-304",
        "name": "NASA SDO AIA 304 Å",
        "url": "https://sdo.gsfc.nasa.gov/assets/img/latest/latest_1024_0304.jpg",
        "refresh_sec": 3600,
        "category": "solar",
    },
    {
        "id": "sdo-aia-193",
        "name": "NASA SDO AIA 193 Å",
        "url": "https://sdo.gsfc.nasa.gov/assets/img/latest/latest_1024_0193.jpg",
        "refresh_sec": 3600,
        "category": "solar",
    },
    {
        "id": "soho-lasco-c2",
        "name": "SOHO LASCO C2 Coronagraph",
        "url": "https://soho.nascom.nasa.gov/data/LATEST/current_c2.gif",
        "refresh_sec": 1800,
        "category": "solar",
    },
    {
        "id": "soho-lasco-c3",
        "name": "SOHO LASCO C3 Coronagraph",
        "url": "https://soho.nascom.nasa.gov/data/LATEST/current_c3.gif",
        "refresh_sec": 1800,
        "category": "solar",
    },
    {
        "id": "noaa-aurora-ovation-north",
        "name": "NOAA Ovation Aurora Forecast (N. Hemisphere)",
        "url": "https://services.swpc.noaa.gov/images/animations/ovation/north/latest.jpg",
        "refresh_sec": 300,
        "category": "space-weather",
    },
    {
        "id": "noaa-aurora-ovation-south",
        "name": "NOAA Ovation Aurora Forecast (S. Hemisphere)",
        "url": "https://services.swpc.noaa.gov/images/animations/ovation/south/latest.jpg",
        "refresh_sec": 300,
        "category": "space-weather",
    },
    {
        "id": "swpc-kp-plot",
        "name": "NOAA SWPC Planetary K-index Plot",
        "url": "https://services.swpc.noaa.gov/images/planetary-k-index.png",
        "refresh_sec": 900,
        "category": "space-weather",
    },
    {
        "id": "swpc-xray-flux",
        "name": "GOES X-Ray Flux Plot",
        "url": "https://services.swpc.noaa.gov/images/goes-xray-flux.gif",
        "refresh_sec": 300,
        "category": "space-weather",
    },
    {
        "id": "swpc-enlil",
        "name": "WSA-Enlil Solar Wind Prediction",
        "url": "https://services.swpc.noaa.gov/images/animations/enlil/latest.jpg",
        "refresh_sec": 7200,
        "category": "space-weather",
    },
    {
        "id": "nasa-epic-earth",
        "name": "NASA DSCOVR EPIC Natural Color",
        "url": "https://epic.gsfc.nasa.gov/archive/natural/latest.jpg",
        "refresh_sec": 3600,
        "category": "earth-observ",
    },
    # Weather Maps & Radar
    {
        "id": "nws-radar-national",
        "name": "NWS National Radar Mosaic (CONUS)",
        "url": "https://radar.weather.gov/ridge/Conus/RadarImg/latest_radaronly.png",
        "refresh_sec": 600,
        "category": "weather",
    },
    {
        "id": "nws-surface-analysis",
        "name": "NOAA WPC Surface Analysis",
        "url": "https://www.wpc.ncep.noaa.gov/archives/sfc/usa_latest.gif",
        "refresh_sec": 1800,
        "category": "weather",
    },
    {
        "id": "spc-day1-outlook",
        "name": "SPC Day-1 Convective Outlook",
        "url": "https://www.spc.noaa.gov/products/outlook/day1otlk_1200.gif",
        "refresh_sec": 3600,
        "category": "weather",
    },
    {
        "id": "spc-day2-outlook",
        "name": "SPC Day-2 Convective Outlook",
        "url": "https://www.spc.noaa.gov/products/outlook/day2otlk_0600.gif",
        "refresh_sec": 3600,
        "category": "weather",
    },
    {
        "id": "nhc-atlantic-2day",
        "name": "NHC Atlantic 2-Day Tropical Outlook",
        "url": "https://www.nhc.noaa.gov/xgtwo/two_atl_2d0.png",
        "refresh_sec": 10800,
        "category": "weather",
    },
    {
        "id": "nhc-pacific-2day",
        "name": "NHC East-Pac 2-Day Tropical Outlook",
        "url": "https://www.nhc.noaa.gov/xgtwo/two_epac_2d0.png",
        "refresh_sec": 10800,
        "category": "weather",
    },
    {
        "id": "nohrsc-snow-anal",
        "name": "NOHRSC National Snow Analysis",
        "url": "https://www.nohrsc.noaa.gov/snow_model/images/full/National/nsm_depth_usa.png",
        "refresh_sec": 43200,
        "category": "weather",
    },
    {
        "id": "noaa-sst-anomaly",
        "name": "NOAA Daily SST Anomaly",
        "url": "https://www.ospo.noaa.gov/data/sst/anomaly/2025/anomnight.20250611.gif",
        "refresh_sec": 86400,
        "category": "weather",
    },
    {
        "id": "noaa-blitzortung-na",
        "name": "Blitzortung Real-Time Lightning (NA)",
        "url": "https://map.blitzortung.org/static/images/acc_NA.png",
        "refresh_sec": 60,
        "category": "lightning",
    },
    {
        "id": "windy-global-wind",
        "name": "Windy.com Global Wind Overlay PNG",
        "url": "https://tiles.windy.com/tiles/v9.1/station/2025/06/13/05/0/0.png",
        "refresh_sec": 600,
        "category": "weather",
    },
    # Volcano & Geophysical Cams
    {
        "id": "kilauea-halemaumau",
        "name": "USGS Kīlauea Halemaʻumaʻu Overlook",
        "url": "https://www.usgs.gov/sites/default/files/styles/scale_1000/public/thumbnails/image/housingradar_webcam.jpg",
        "refresh_sec": 300,
        "category": "volcano",
    },
    {
        "id": "mauna-loa-summit",
        "name": "USGS Mauna Loa Mokuʻāweoweo Caldera",
        "url": "https://www.usgs.gov/volcanoes/mauna-loa/webcams/MLcam.jpg",
        "refresh_sec": 300,
        "category": "volcano",
    },
    {
        "id": "mount-st-helens-johnston",
        "name": "Mount St. Helens – Johnston Ridge",
        "url": "https://www.fs.usda.gov/Internet/FSE_MEDIA/sthelens.jpg",
        "refresh_sec": 300,
        "category": "volcano",
    },
    {
        "id": "popocatepetl-vista",
        "name": "CENAPRED Popocatépetl",
        "url": "https://www.cenapred.unam.mx/popo/UltimaImagen.jpg",
        "refresh_sec": 60,
        "category": "volcano",
    },
    {
        "id": "sakurajima-live",
        "name": "Sakurajima Volcano (Kagoshima)",
        "url": "https://www.qsr.mlit.go.jp/n-kanri/vol_img/volcam.jpg",
        "refresh_sec": 60,
        "category": "volcano",
    },
    {
        "id": "etna-piano-provenzana",
        "name": "Etna Nord Piano Provenzana",
        "url": "https://images.vivienna.com/webcam/etna_nord.jpg",
        "refresh_sec": 60,
        "category": "volcano",
    },
    {
        "id": "stromboli-pizzo",
        "name": "INGV Stromboli (Pizzo)",
        "url": "https://www.ct.ingv.it/it/webcam/str_pizzo.jpg",
        "refresh_sec": 60,
        "category": "volcano",
    },
    {
        "id": "nevado-del-ruiz",
        "name": "Nevado del Ruiz Volcano",
        "url": "https://www.ideam.gov.co/documents/21021/115139/nevada_del_ruiz.jpg",
        "refresh_sec": 300,
        "category": "volcano",
    },
    {
        "id": "yellowstone-old-faithful",
        "name": "Yellowstone Old Faithful Geyser",
        "url": "https://www.nps.gov/webcams-yell/oldfaithful.jpg",
        "refresh_sec": 30,
        "category": "national-park",
    },
    # National-Park & Nature Cams
    {
        "id": "yosemite-half-dome",
        "name": "Yosemite Half Dome Cam",
        "url": "https://www.nps.gov/webcams-yose/hd.jpg",
        "refresh_sec": 300,
        "category": "national-park",
    },
    {
        "id": "yosemite-falls",
        "name": "Yosemite Falls Cam",
        "url": "https://www.nps.gov/webcams-yose/yosemitefalls.jpg",
        "refresh_sec": 300,
        "category": "national-park",
    },
    {
        "id": "glacier-apgar",
        "name": "Glacier NP – Apgar Mountains",
        "url": "https://www.nps.gov/webcams-glac/apg.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "grand-canyon-yavapai",
        "name": "Grand Canyon Yavapai Point",
        "url": "https://www.nps.gov/webcams-grca/cams/yav_full.jpg",
        "refresh_sec": 300,
        "category": "national-park",
    },
    {
        "id": "denali-wonder-lake",
        "name": "Denali Wonder Lake Cam",
        "url": "https://www.nps.gov/webcams-dena/WonderLake.jpg",
        "refresh_sec": 900,
        "category": "national-park",
    },
    {
        "id": "rocky-mountain-alpine",
        "name": "Rocky Mountain Alpine Visitor Center",
        "url": "https://www.nps.gov/webcams-romo/alpinevc.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "badlands-pinnacles",
        "name": "Badlands Pinnacles Cam",
        "url": "https://www.nps.gov/webcams-badl/pinnacles.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "acadia-cadillac",
        "name": "Acadia Cadillac Mountain",
        "url": "https://www.nps.gov/webcams-acad/Cadillac.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "zion-kolob",
        "name": "Zion Kolob Canyons Cam",
        "url": "https://www.nps.gov/webcams-zion/kolob.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "arches-park-entrance",
        "name": "Arches NP Entrance Cam",
        "url": "https://www.nps.gov/webcams-arch/ARCHEntrance.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "mesa-verde-spruce",
        "name": "Mesa Verde Spruce Tree House Cam",
        "url": "https://www.nps.gov/webcams-meve/MEVE_Spruce.jpg",
        "refresh_sec": 900,
        "category": "national-park",
    },
    {
        "id": "everglades-flamingo",
        "name": "Everglades Flamingo Marina",
        "url": "https://www.nps.gov/webcams-ever/flamingo.jpg",
        "refresh_sec": 900,
        "category": "national-park",
    },
    {
        "id": "grand-teton-jackson",
        "name": "Grand Teton Jackson Lake Cam",
        "url": "https://www.nps.gov/webcams-grte/jacksonlake.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "shenandoah-big-meadows",
        "name": "Shenandoah Big Meadows",
        "url": "https://www.nps.gov/webcams-shen/bigmeadows.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "denali-eielson",
        "name": "Denali Eielson Visitor Center",
        "url": "https://www.nps.gov/webcams-dena/eielson.jpg",
        "refresh_sec": 900,
        "category": "national-park",
    },
    # City / Landmark Cams
    {
        "id": "times-square",
        "name": "Times Square EarthCam",
        "url": "https://images.earthcam.com/ec_metros/ourcams/ts.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "seattle-space-needle",
        "name": "Seattle Space Needle Cam",
        "url": "https://www.seattlespaceneedle.com/webcam/spaceneedle.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "chicago-skyline-adler",
        "name": "Chicago Skyline – Adler Planetarium",
        "url": "https://www.adlerplanetarium.org/images/webcam.jpg",
        "refresh_sec": 300,
        "category": "city",
    },
    {
        "id": "sanfran-sutro",
        "name": "San Francisco Sutro Tower View",
        "url": "https://www.alertwildfire.org/images/ALERT2/AXIS-SUTRO-S_M.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "miami-south-beach",
        "name": "Miami South Beach Cam",
        "url": "https://static.earthcam.com/multimedia/webcams/sobe/1.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "london-trafalgar",
        "name": "London Trafalgar Square",
        "url": "https://images.earthcam.com/ec_metros/ourcams/trafalgar.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "paris-eiffel",
        "name": "Paris Eiffel Tower Cam",
        "url": "https://images.earthcam.com/ec_metros/ourcams/eiffel.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "tokyo-shibuya",
        "name": "Tokyo Shibuya Crossing",
        "url": "https://static.camera-web.jp/shibuya/cam.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "sydney-harbour",
        "name": "Sydney Harbour Bridge",
        "url": "https://www.seesydney.com/webcams/harbour.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "dubai-marina",
        "name": "Dubai Marina Skyline",
        "url": "https://webcams.dubai-marina.com/marina.jpg",
        "refresh_sec": 120,
        "category": "city",
    },
    # Ocean / Coastal & Surf
    {
        "id": "surfline-pipeline",
        "name": "Oahu Pipeline Surf Cam",
        "url": "https://cams.surfline.com/camera/Pipeline/latest.jpg",
        "refresh_sec": 30,
        "category": "surf",
    },
    {
        "id": "monterey-bay-aquarium",
        "name": "Monterey Bay Aquarium – Outer Bay",
        "url": "https://www.montereybayaquarium.org/-/m/images/webcams/outerbay.jpg",
        "refresh_sec": 30,
        "category": "ocean",
    },
    {
        "id": "glos-south-haven",
        "name": "Great Lakes – South Haven Lighthouse",
        "url": "https://glbuoys.glos.us/SouthHaven/southhaven.jpg",
        "refresh_sec": 300,
        "category": "ocean",
    },
    {
        "id": "noaa-portland-head",
        "name": "NOAA PORTS – Portland Head",
        "url": "https://tidesandcurrents.noaa.gov/ports_assets/images/por0001.jpg",
        "refresh_sec": 300,
        "category": "ocean",
    },
    {
        "id": "gulf-cleargo",
        "name": "Gulf of Mexico – ClearGO Buoy Cam",
        "url": "https://www.ndbc.noaa.gov/webcam/cleargo.jpg",
        "refresh_sec": 600,
        "category": "ocean",
    },
    # Traffic / Roadway Cams
    {
        "id": "wsdot-snoqualmie",
        "name": "WSDOT I-90 Snoqualmie Pass",
        "url": "https://images.wsdot.wa.gov/nw/090/090vc00526.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "caltrans-donner",
        "name": "Caltrans I-80 Donner Summit",
        "url": "https://cwwp2.dot.ca.gov/data/d3/cctv/image/donner.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "idot-jane-addams",
        "name": "IDOT I-90 Jane Addams @ Roselle",
        "url": "https://idot.trafficwise.org/uscams/J005.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "gdot-i75-midtown",
        "name": "GDOT I-75 @ 17th St (Atlanta)",
        "url": "https://511georgia.org/cctvpic/someFutureId.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "txdot-i45-downtown",
        "name": "TxDOT I-45 Downtown Houston",
        "url": "https://traffic.txdot.gov/cctv/region_houston/45/00123.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "mto-401-weston",
        "name": "Ontario Hwy 401 @ Weston",
        "url": "https://www.mto.gov.on.ca/english/traveller/compass/images/camera?id=401-204-0",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "nysdot-tzb",
        "name": "NYS Thruway Gov Mario M. Cuomo Bridge",
        "url": "https://www.thruway.ny.gov/travelers/cameras/images/tzb_north.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    {
        "id": "wsdot-seattle-i5",
        "name": "WSDOT I-5 @ Seneca St (Seattle)",
        "url": "https://images.wsdot.wa.gov/sw/005/005vc16587.jpg",
        "refresh_sec": 60,
        "category": "traffic",
    },
    # Aviation / Space Launch / ISS
    {
        "id": "iss-hdev",
        "name": "ISS Earth-View (HD Camera)",
        "url": "https://iss.stormway.ru/iss.jpg",
        "refresh_sec": 10,
        "category": "space",
    },
    {
        "id": "nasa-pad39a",
        "name": "NASA KSC Pad 39A Cam",
        "url": "https://science.ksc.nasa.gov/multimedia/images/flames/ksc-pad39a.jpg",
        "refresh_sec": 30,
        "category": "space",
    },
    {
        "id": "spacex-starbase-mid",
        "name": "SpaceX Starbase Mid-Tower",
        "url": "https://www.spadre.com/starbase.jpg",
        "refresh_sec": 15,
        "category": "space",
    },
    {
        "id": "perseverance-front-hazcam",
        "name": "Mars 2020 Perseverance Front Hazcam",
        "url": "https://mars.nasa.gov/msl-raw-images/FRONT_HAZCAM_LEFT_A/latest.jpg",
        "refresh_sec": 21600,
        "category": "mars",
    },
    {
        "id": "jwst-nircam",
        "name": "JWST NIRCam “Picture of Week”",
        "url": "https://www.jwst.nasa.gov/content/webbLaunch/assets/images/jwst_potw.jpg",
        "refresh_sec": 604800,
        "category": "space",
    },
    {
        "id": "rainier-paradise",
        "name": "Mount Rainier Paradise Cam",
        "url": "https://www.nps.gov/webcams-mora/paradise.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "olympic-hurricane-ridge",
        "name": "Olympic Hurricane Ridge",
        "url": "https://www.nps.gov/webcams-olym/hurricane.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "craterlake-lodge",
        "name": "Crater Lake Lodge Cam",
        "url": "https://www.nps.gov/webcams/crla.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "bryce-canyon",
        "name": "Bryce Canyon Amphitheater",
        "url": "https://www.nps.gov/webcams/brca.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "carlsbad-entrance",
        "name": "Carlsbad Caverns Entrance",
        "url": "https://www.nps.gov/webcams/cave/entrance.jpg",
        "refresh_sec": 600,
        "category": "national-park",
    },
    {
        "id": "test-pattern",
        "name": "Test Pattern",
        "url": "http://127.0.0.1:8082/test_pattern.mjpg",
        "refresh_sec": 5,
        "category": "utility",
    },
    {
        "id": "niagara-falls",
        "name": "Niagara Falls Cam",
        "url": "https://www.niagarafallslive.com/niagara-falls-webcam.jpg",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "mtwashington-summit",
        "name": "Mt Washington Summit",
        "url": "https://www.mountwashington.org/cams/summit.jpg",
        "refresh_sec": 300,
        "category": "weather",
    },
    {
        "id": "machu-picchu",
        "name": "Machu Picchu Cam",
        "url": "https://www.skylinewebcams.com/webcam/peru/cusco/machu-picchu.html",
        "refresh_sec": 600,
        "category": "city",
    },
    {
        "id": "santorini-caldera",
        "name": "Santorini Caldera View",
        "url": "https://www.skylinewebcams.com/webcam/greece/cyclades/santorini.html",
        "refresh_sec": 300,
        "category": "city",
    },
    {
        "id": "rio-copacabana",
        "name": "Rio Copacabana Beach",
        "url": "https://www.skylinewebcams.com/webcam/brasil/rio-de-janeiro/copacabana.html",
        "refresh_sec": 60,
        "category": "city",
    },
    {
        "id": "svalbard-longyearbyen",
        "name": "Svalbard Longyearbyen",
        "url": "https://www.svalbard.com/webcam.jpg",
        "refresh_sec": 600,
        "category": "city",
    },
    {
        "id": "toronto-cn-tower",
        "name": "Toronto CN Tower Cam",
        "url": "https://www.seetorontonow.com/wp-content/uploads/2017/04/cam1.jpg",
        "refresh_sec": 300,
        "category": "city",
    },
]
