import socket
from zoneinfo import available_timezones

import psutil

SETTINGS_TOOLTIPS = {
    "API_KEY": "Generated by the platform",  # pragma: allowlist secret
    "CHATGPT_KEY": "Required for ChatGPT features",
    "DATABASE_PATH": "Location of the SQLite database",
    "PORT": "Web server port",
    "USER_NAME": "Interface login user",
    "MAX_WORKERS": "Concurrent worker threads",
    "LLM_CAPTION_PROMPT": (
        "System prompt used for image captions. Supports the $datetime token and"
        " can span multiple lines."
    ),
    "LLM_SUMMARY_PROMPT": (
        "System prompt for daily summaries. May be multi-line and also supports"
        " the $datetime token."
    ),
    "MAX_RAW_DATA_SIZE": "Raw data threshold",
    "MAX_IMAGE_RETENTION_AGE": "Image retention days",
    "MAX_VIDEO_RETENTION_AGE": "Video retention days",
    "MAX_IN_PROCESS_VIDEO_SIZE": "Temporary video size cap",
    "LOG_LEVEL": "Python logging level",
    "FFMPEG_PATH": "Location of the FFmpeg binary",
    "FFMPEG_HWACCEL": "Enable ffmpeg hardware acceleration when supported",
    "FFMPEG_THREADS": "Threads for video processing",
    "LIVE_FALLBACK_FPS": "Frame rate for still image streams",
    "LIVE_MAX_FAILURES": "Max retries for live streams",
    "CHYRON_SPEED": "Duration of caption banner in seconds",
    "CRAWLER_STARTUP_SPREAD": "Minutes to stagger initial crawler runs",
    "EMAIL_ENABLED": "Toggle email notifications",
    "SMS_ENABLED": "Toggle SMS notifications",
    "CAP_ENABLED": "Toggle CAP notifications",
    "EMAIL_SMTP_SERVER": "SMTP server address",
    "EMAIL_RECIPIENTS": "Notification recipients",
    "TWILIO_SID": "Twilio account SID",
    "TWILIO_TOKEN": "Twilio authentication token",
    "TWILIO_NUMBER": "Sending phone number",
    "CLOCK_OVERLAY": "Show clock on video overlay",
    "CLOCK_DIGITAL": "Display clock as digital text",
    "CLOCK_NAVBAR": "Show clock in the navigation bar",
    "HEALTH_STATUS_ALWAYS_VISIBLE": "Keep the system performance icon visible",
    "MAX_COMPRESSED_VIDEO_AGE": "Days to keep archived videos",
    "NAV_ICON": (
        "PNG file used for the navigation logo. Upload a custom image from the "
        "Interface tab or choose the default option to restore it."
    ),
    "UA": "User-Agent string for website requests",
    "HOST": "Address to bind the server",
    "LANG": "Default interface language",
    "TZ": "Default time zone",
    "NAME": "Application name shown in the UI",
    "DEBUG": "Enable debug output",
    "DEBUG_MODE": "Enable debug mode features",
    "FLASK_LOG_LEVEL": "Flask logging level",
    "ENFORCE_DOMAIN_IN_HOST": "Force FQDN in host header",
    "LOG_RATE_LIMIT_SEC": "Seconds between repeated logs",
    "LOG_COLOR": "Colorize log output",
    "SESSION_COOKIE_SECURE": "Use secure cookies over HTTPS",
    "SESSION_COOKIE_HTTPONLY": "Disallow JavaScript access to session cookie",
    "SESSION_TIMEOUT_MINUTES": "Idle minutes before auto logout",
    "AUTO_LOGIN_DAYS": "Remember login for this many days",
    "ALLOW_BOTS": "Allow search engine indexing",
    "AUTO_UPDATE_BRANCH": "Branch to auto-update from",
    "SCHEDULER_API_ENABLED": "Enable the APScheduler REST API",
    "SCREENSHOT_DIRECTORY": "Directory for captured screenshots",
    "VIDEO_DIRECTORY": "Directory for downloaded videos",
    "CLIPS_DIRECTORY": "Directory for generated clips",
    "SUMMARIES_DIRECTORY": "Deprecated summaries path",
    "DOCS_DIRECTORY": "Path to built documentation",
    "CLIP_MODEL_PATH": "Path to ONNX model for object filtering",
    "CLIP_MODEL_NAME": "CLIP model used for object filtering",
    "LLM_MODEL_VERSION": "Version of the language model to use",
    "LIVE_MAX_RETRY_DELAY": "Max delay between live stream restarts",
    "DEFAULT_CLIP_DURATION": "Default clip length returned by /clip",
    "MAX_CLIP_AGE_MINUTES": "Minutes before temporary clips are purged",
    "CLIP_REFRESH_MAX_CAMERAS": "Skip clip refresh when more than this many cameras",
    "PROBE_SIZE_DEFAULT": "FFmpeg probe size for HTTP/HTTPS streams",
    "PROBE_SIZE_RTSP": "Probe size for RTSP streams",
    "PROBE_SIZE_OTHER": "Probe size for other protocols",
    "ANALYZE_DURATION_DEFAULT": "FFmpeg analyzeduration for HTTP/HTTPS streams",
    "ANALYZE_DURATION_RTSP": "Analyzeduration for RTSP streams",
    "ANALYZE_DURATION_OTHER": "Analyzeduration for other protocols",
    "NUM_FRAMES": "Number of frames to capture",
    "CAPTURE_TIMEOUT": "Seconds before capture times out",
    "EMAIL_SMTP_PORT": "SMTP server port",
    "EMAIL_SMTP_TIMEOUT": "Seconds to wait for SMTP connection",
    "EMAIL_USE_TLS": "Use TLS when connecting to SMTP server",
    "EMAIL_USERNAME": "SMTP authentication user name",
    "EMAIL_PASSWORD": "SMTP authentication password",  # pragma: allowlist secret
    "TWILIO_FROM_NUMBER": "Phone number used as SMS sender",
    "VAPID_PUBLIC_KEY": "Web Push public key",
    "VAPID_PRIVATE_KEY": "Web Push private key",  # pragma: allowlist secret
    "CAP_ENDPOINT": "URL accepting CAP alerts",
    "CAP_SENDER": "Identifier used in CAP sender field",
    "MCP_SERVER_COMMAND": "Command used to start the MCP server",
    "MCP_SERVER_URL": "URL of the MCP server",
    "WATCHDOG_FAILURE_THRESHOLD": "Failed checks before restart",
    "WATCHDOG_RESTART_COOLDOWN": "Seconds between automatic restarts",
    "WATCHDOG_MAX_FILE_HANDLES": "Open file handle limit",
    "WATCHDOG_CPU_THRESHOLD": "CPU usage percentage threshold",
    "WATCHDOG_MEMORY_THRESHOLD": "Memory usage percentage threshold",
}

# Predefined choices for select fields on the settings page. The "Other"
# option reveals a text input allowing custom values.


def _host_choices() -> list[str]:
    choices = ["0.0.0.0", "127.0.0.1", "localhost"]
    try:
        for addrs in psutil.net_if_addrs().values():
            for addr in addrs:
                if addr.family == socket.AF_INET and not addr.address.startswith(
                    "127."
                ):
                    if addr.address not in choices:
                        choices.append(addr.address)
    except Exception:
        pass
    return choices


SETTINGS_CHOICES = {
    "HOST": _host_choices(),
    "LANG": [
        "en-US",  # English
        "es-ES",  # Spanish
        "fr-FR",  # French
        "de-DE",  # German
        "zh-CN",  # Chinese Simplified
        "ja-JP",  # Japanese
        "pt-BR",  # Portuguese (Brazil)
        "hi-IN",  # Hindi
        "ar-SA",  # Arabic
        "ru-RU",  # Russian
    ],
    "LOG_LEVEL": ["DEBUG", "INFO", "WARN", "ERROR", "CRITICAL"],
    "FLASK_LOG_LEVEL": ["DEBUG", "INFO", "WARN", "ERROR", "CRITICAL"],
    "TZ": sorted(available_timezones()),
}

# Settings categories used to group configuration values on the settings page.
# Keys are tab labels while the lists contain setting names assigned to each
# category. Any values not present here fall under the "Other" tab.
SETTINGS_GROUPS = {
    "General": [
        "NAME",
        "VERSION",
        "LANG",
        "TZ",
        "HOST",
        "PORT",
        "DEBUG",
        "DEBUG_MODE",
        "MAX_WORKERS",
        "LOG_LEVEL",
        "FLASK_LOG_LEVEL",
        "CLOCK_OVERLAY",
        "CLOCK_DIGITAL",
        "CLOCK_NAVBAR",
    ],
    "Admin": [
        "USER_NAME",
        "USER_PASSWORD_HASH",
        "SECRET_KEY",
        "API_KEY",
        "SSO_TOKEN",
        "SSO_USERNAME",
        "CHATGPT_KEY",
        "SESSION_COOKIE_SECURE",
        "SESSION_COOKIE_HTTPONLY",
        "SESSION_TIMEOUT_MINUTES",
    ],
    "Capture": [
        "DATABASE_PATH",
        "LOGGING_PATH",
        "BACKUP_PATH",
        "SCREENSHOT_DIRECTORY",
        "VIDEO_DIRECTORY",
        "SUMMARIES_DIRECTORY",
        "NUM_FRAMES",
        "CAPTURE_TIMEOUT",
        "PROBE_SIZE_DEFAULT",
        "PROBE_SIZE_RTSP",
        "PROBE_SIZE_OTHER",
        "ANALYZE_DURATION_DEFAULT",
        "ANALYZE_DURATION_RTSP",
        "ANALYZE_DURATION_OTHER",
        "LIVE_FALLBACK_FPS",
        "LIVE_MAX_FAILURES",
        "CHYRON_SPEED",
        "WATCHDOG_FAILURE_THRESHOLD",
        "WATCHDOG_RESTART_COOLDOWN",
        "WATCHDOG_MAX_FILE_HANDLES",
        "CRAWLER_STARTUP_SPREAD",
        "DISCOVERY_AUTOSTART",
        "CLIP_MODEL_NAME",
        "FFMPEG_PATH",
        "FFPROBE_PATH",
        "FFMPEG_HWACCEL",
        "FFMPEG_THREADS",
    ],
    "Advanced": [
        "EMAIL_ENABLED",
        "SMS_ENABLED",
        "CAP_ENABLED",
        "EMAIL_SENDER",
        "EMAIL_RECIPIENTS",
        "EMAIL_SMTP_SERVER",
        "EMAIL_SMTP_PORT",
        "EMAIL_USE_TLS",
        "EMAIL_USERNAME",
        "EMAIL_PASSWORD",
        "TWILIO_SID",
        "TWILIO_TOKEN",
        "TWILIO_NUMBER",
        "MCP_SERVER_COMMAND",
        "MCP_SERVER_URL",
        "CLOCK_OVERLAY",
        "CLOCK_DIGITAL",
        "CLOCK_NAVBAR",
        "CAP_ENDPOINT",
        "CAP_SENDER",
    ],
}

# Fields that should only allow numeric values on the settings page.
NUMERIC_FIELDS = {
    "MAX_WORKERS",
    "EMAIL_SMTP_PORT",
    "LIVE_FALLBACK_FPS",
    "LIVE_MAX_FAILURES",
    "CHYRON_SPEED",
    "WATCHDOG_FAILURE_THRESHOLD",
    "WATCHDOG_RESTART_COOLDOWN",
    "WATCHDOG_MAX_FILE_HANDLES",
}

# Fields that expect email addresses.
EMAIL_FIELDS = {"EMAIL_SENDER", "EMAIL_RECIPIENTS"}

# Settings that are hidden behind the advanced toggle on the UI. Their
# corresponding form inputs are disabled unless advanced mode is enabled.
LOCKED_SETTINGS = {"CLIP_MODEL_NAME"}

# Example placeholders displayed in the settings form.
SETTINGS_PLACEHOLDERS = {
    "EMAIL_SENDER": "your-email@example.com",
    "EMAIL_RECIPIENTS": "recipient1@example.com,recipient2@example.com",
    "EMAIL_SMTP_SERVER": "smtp.example.com",
    "EMAIL_USERNAME": "your-username",
    "CAP_ENDPOINT": "https://alert.example.com",
    "CAP_SENDER": "glimpser@example.com",
}
