"""Tooltip text and related configuration for the settings interface.

The module exposes ``SETTINGS_TOOLTIPS`` along with helper dictionaries such
as ``SETTINGS_CHOICES`` and ``SETTINGS_GROUPS`` that organize available options
on the configuration page.
"""

import socket
from zoneinfo import available_timezones

import psutil

SETTINGS_TOOLTIPS = {
    "API_KEY": (
        "Generated by the platform and used to authorize API calls. Keep this "
        "value secret to prevent unauthorized access."
    ),
    "CHATGPT_KEY": (
        "OpenAI key required for AI captioning and summarization features. "
        "Leave blank to disable these integrations."
    ),
    "DATABASE_PATH": (
        "Filesystem location of the SQLite database. Change it if you move the "
        "database file."
    ),
    "PORT": (
        "TCP port used by the built-in web server. The default is 8082 but any "
        "available port may be chosen."
    ),
    "DANGER_PORT": (
        "Port used by Chrome for remote debugging when Danger mode is enabled. "
        "Change this if you launch Chrome with --remote-debugging-port on a "
        "different value."
    ),
    "USER_NAME": (
        "Default username for logging into the interface. Combine with the "
        "password hash for authentication."
    ),
    "MAX_WORKERS": (
        "Number of worker threads allowed to run capture jobs in parallel. "
        "Set close to your camera count."
    ),
    "LLM_CAPTION_PROMPT": (
        "System prompt used for image captions. Supports the $datetime token "
        "and can span multiple lines."
    ),
    "LLM_SUMMARY_PROMPT": (
        "System prompt for daily summaries. May be multi-line and also "
        "supports the $datetime token."
    ),
    "MAX_RAW_DATA_SIZE": (
        "Total size in bytes of raw images and videos allowed before older "
        "files are automatically purged."
    ),
    "MAX_IMAGE_RETENTION_AGE": (
        "Maximum age in days before captured images are deleted to reclaim "
        "storage space."
    ),
    "MAX_VIDEO_RETENTION_AGE": (
        "Maximum number of days video files are kept before being removed."
    ),
    "MAX_IN_PROCESS_VIDEO_SIZE": (
        "Upper limit on temporary video size while capturing. Jobs abort once "
        "this threshold is reached."
    ),
    "LOG_LEVEL": (
        "Python logging verbosity. Options include DEBUG, INFO, WARN, ERROR, "
        "or CRITICAL."
    ),
    "FFMPEG_PATH": (
        "Full path to the ffmpeg binary. Override if ffmpeg is not in your "
        "system PATH."
    ),
    "FFMPEG_HWACCEL": (
        "Enable hardware accelerated encoding when supported by your GPU and "
        "ffmpeg installation."
    ),
    "FFMPEG_THREADS": (
        "Number of threads ffmpeg should use while encoding or decoding video."
    ),
    "LIVE_FALLBACK_FPS": (
        "Frame rate used when live view falls back to periodic screenshots. "
        "Increase if your hardware can keep up."
    ),
    "LIVE_MAX_FAILURES": (
        "Number of ffmpeg errors tolerated in a row before the connection is " "closed."
    ),
    "CHYRON_SPEED": (
        "Number of seconds the caption banner scrolls across the top of the "
        "page. Set to 0 to disable."
    ),
    "CRAWLER_STARTUP_SPREAD": (
        "Minutes used to stagger initial crawler runs across all feeds. This "
        "prevents overwhelming the network at boot."
    ),
    "EMAIL_ENABLED": (
        "Set to True to enable email alerts. SMTP options below must also be "
        "configured."
    ),
    "SMS_ENABLED": (
        "Set to True to send SMS notifications via Twilio. Requires Twilio "
        "credentials."
    ),
    "CAP_ENABLED": (
        "Enable sending Common Alerting Protocol messages. Requires CAP "
        "endpoint configuration."
    ),
    "EMAIL_SMTP_SERVER": (
        "Hostname of the SMTP server used to send notification emails."
    ),
    "EMAIL_RECIPIENTS": (
        "Comma-separated list of email addresses that will receive alerts."
    ),
    "TWILIO_SID": ("Twilio account SID for sending SMS messages."),
    "TWILIO_TOKEN": ("Authentication token paired with the Twilio SID."),
    "TWILIO_NUMBER": ("Phone number that SMS alerts are sent from."),
    "CLOCK_OVERLAY": ("Display a timestamp overlay on captured videos when enabled."),
    "CLOCK_DIGITAL": ("Show the clock as digital text instead of an analog icon."),
    "CLOCK_NAVBAR": ("When enabled, the current time appears in the navigation bar."),
    "HEALTH_STATUS_ALWAYS_VISIBLE": (
        "Keep the system performance indicator visible even when metrics look "
        "normal."
    ),
    "MAX_COMPRESSED_VIDEO_AGE": (
        "Number of days to keep archived videos that have been compressed."
    ),
    "NAV_ICON": (
        "PNG file used for the navigation logo. Upload a custom image from the "
        "Interface tab or choose the default option to restore it."
    ),
    "UA": (
        "User-Agent string sent when requesting remote pages. Modify if a "
        "camera requires a specific identifier."
    ),
    "HOST": (
        "Network address the web server binds to. Use 0.0.0.0 to listen on all "
        "interfaces."
    ),
    "LANG": (
        "Default interface language. Choices include common locale codes such as "
        "en-US or fr-FR."
    ),
    "TZ": (
        "Default time zone used for displaying dates and times in the " "interface."
    ),
    "NAME": ("Human friendly application name displayed throughout the UI."),
    "DEBUG": ("Enable debug output in the logs for troubleshooting."),
    "DEBUG_MODE": ("Turns on additional debug features useful during development."),
    "FLASK_LOG_LEVEL": ("Logging verbosity for Flask's internal messages."),
    "ENFORCE_DOMAIN_IN_HOST": (
        "Require a fully qualified domain name in the Host header of incoming "
        "requests."
    ),
    "LOG_RATE_LIMIT_SEC": (
        "Minimum number of seconds before repeating identical log messages."
    ),
    "LOG_COLOR": (
        "Colorize log output when viewed in a terminal that supports ANSI " "colors."
    ),
    "SESSION_COOKIE_SECURE": (
        "Mark session cookies as secure so they are only sent over HTTPS."
    ),
    "SESSION_COOKIE_HTTPONLY": (
        "Prevent client side scripts from reading the session cookie."
    ),
    "SESSION_TIMEOUT_MINUTES": (
        "Number of idle minutes before the user is automatically logged out."
    ),
    "AUTO_LOGIN_DAYS": (
        "Remember the user for this many days when the 'stay logged in' option "
        "is selected."
    ),
    "SKIP_LOGIN_SUBNETS": (
        "Comma-separated CIDR blocks that can access non-admin pages without "
        "logging in."
    ),
    "ALLOW_BOTS": (
        "Allow search engines to index the site. Disable for private " "installations."
    ),
    "AUTO_UPDATE_BRANCH": (
        "Git branch to pull automatic updates from when auto update is " "enabled."
    ),
    "SCHEDULER_API_ENABLED": (
        "Expose the APScheduler REST API for remote job management."
    ),
    "SCREENSHOT_DIRECTORY": (
        "Directory on disk where captured screenshots are stored."
    ),
    "VIDEO_DIRECTORY": ("Directory used to store downloaded video files."),
    "CLIPS_DIRECTORY": ("Directory containing generated video clips for sharing."),
    "SUMMARIES_DIRECTORY": (
        "Deprecated path for summary files, kept for backward compatibility."
    ),
    "DOCS_DIRECTORY": ("Path to the built documentation site."),
    "CLIP_MODEL_PATH": ("Location of the ONNX model used for object filtering."),
    "CLIP_MODEL_NAME": ("Name of the CLIP model used for object filtering."),
    "LLM_MODEL_VERSION": (
        "Version identifier for the language model used with captioning."
    ),
    "LIVE_MAX_RETRY_DELAY": (
        "Maximum delay between attempts to restart a failed live stream."
    ),
    "DEFAULT_CLIP_DURATION": (
        "Default number of seconds returned when generating clips via the /clip "
        "endpoint."
    ),
    "MAX_CLIP_AGE_MINUTES": ("Minutes before temporary clips are purged from storage."),
    "CLIP_REFRESH_MAX_CAMERAS": (
        "Skip clip refresh when more than this many cameras are configured to "
        "avoid heavy disk usage."
    ),
    "PROBE_SIZE_DEFAULT": (
        "ffmpeg probe size used for HTTP or HTTPS streams. Adjust if streams "
        "fail to open."
    ),
    "PROBE_SIZE_RTSP": ("Probe size specifically for RTSP streams."),
    "PROBE_SIZE_OTHER": ("Probe size for protocols other than HTTP or RTSP."),
    "ANALYZE_DURATION_DEFAULT": (
        "ffmpeg analyzeduration value for HTTP or HTTPS streams."
    ),
    "ANALYZE_DURATION_RTSP": ("Analyzeduration used when connecting to RTSP streams."),
    "ANALYZE_DURATION_OTHER": ("Analyzeduration for all other protocols."),
    "NUM_FRAMES": ("Number of frames to capture when grabbing still images."),
    "CAPTURE_TIMEOUT": ("Seconds before an individual capture attempt times out."),
    "EMAIL_SMTP_PORT": ("Port number to connect to on the SMTP server."),
    "EMAIL_SMTP_TIMEOUT": (
        "Time in seconds to wait for a response from the SMTP server."
    ),
    "EMAIL_USE_TLS": ("Enable TLS encryption when connecting to the SMTP server."),
    "EMAIL_USERNAME": ("User name for authenticating with the SMTP server."),
    "EMAIL_PASSWORD": (
        "Password used to authenticate with the SMTP server."  # pragma: allowlist secret
    ),
    "TWILIO_FROM_NUMBER": ("Phone number configured as the SMS sender in Twilio."),
    "VAPID_PUBLIC_KEY": ("Public key used for Web Push notifications."),
    "VAPID_PRIVATE_KEY": (
        "Private key used for Web Push notifications."  # pragma: allowlist secret
    ),
    "NOTIFY_ON_MOTION": ("Send push notifications whenever motion is detected."),
    "NOTIFY_ON_CAPTION": ("Send push notifications when a new caption is generated."),
    "CAP_ENDPOINT": ("URL that accepts Common Alerting Protocol messages."),
    "CAP_SENDER": ("Identifier used in the CAP sender field."),
    "MCP_SERVER_COMMAND": ("Command line used to start the MCP server when enabled."),
    "MCP_SERVER_URL": ("URL of the MCP server for remote clip processing."),
    "WATCHDOG_FAILURE_THRESHOLD": (
        "Number of health check failures before the watchdog initiates a restart."
    ),
    "WATCHDOG_RESTART_COOLDOWN": (
        "Seconds to wait between automatic restarts triggered by the watchdog."
    ),
    "WATCHDOG_MAX_FILE_HANDLES": (
        "Upper limit of open file handles before a restart is triggered."
    ),
    "WATCHDOG_CPU_THRESHOLD": (
        "CPU usage percentage that will trigger a watchdog restart."
    ),
    "WATCHDOG_MEMORY_THRESHOLD": (
        "Memory usage percentage that will trigger a watchdog restart."
    ),
    "FFPROBE_PATH": (
        "Full path to the ffprobe executable used to inspect media files."
    ),
    "DISCOVERY_AUTOSTART": (
        "Automatically start camera discovery on launch. Toggle off to disable "
        "scanning at startup."
    ),
    "EMAIL_SENDER": (
        "Address used in the From header when sending notification emails."
    ),
    "SECRET_KEY": (
        "Flask session signing key. Changing this will invalidate existing "
        "sessions."  # pragma: allowlist secret
    ),
    "SSO_TOKEN": (
        "API token used for single sign-on integration."  # pragma: allowlist secret
    ),
    "SSO_USERNAME": (
        "Default username provided to the SSO system when authenticating."
    ),
    "USER_PASSWORD_HASH": (
        "BCrypt hashed login password stored for the default user."  # pragma: allowlist secret
    ),
    "VERSION": (
        "Glimpser package version displayed in the footer and used for cache "
        "busting."
    ),
}

# Predefined choices for select fields on the settings page. The "Other"
# option reveals a text input allowing custom values.


def _host_choices() -> list[str]:
    choices = ["0.0.0.0", "127.0.0.1", "localhost"]
    try:
        for addrs in psutil.net_if_addrs().values():
            for addr in addrs:
                if addr.family == socket.AF_INET and not addr.address.startswith(
                    "127."
                ):
                    if addr.address not in choices:
                        choices.append(addr.address)
    except Exception:
        pass
    return choices


SETTINGS_CHOICES = {
    "HOST": _host_choices(),
    "LANG": [
        "en-US",  # English
        "es-ES",  # Spanish
        "fr-FR",  # French
        "de-DE",  # German
        "zh-CN",  # Chinese Simplified
        "ja-JP",  # Japanese
        "pt-BR",  # Portuguese (Brazil)
        "hi-IN",  # Hindi
        "ar-SA",  # Arabic
        "ru-RU",  # Russian
    ],
    "LOG_LEVEL": ["DEBUG", "INFO", "WARN", "ERROR", "CRITICAL"],
    "FLASK_LOG_LEVEL": ["DEBUG", "INFO", "WARN", "ERROR", "CRITICAL"],
    "TZ": sorted(available_timezones()),
}

# Settings categories used to group configuration values on the settings page.
# Keys are tab labels while the lists contain setting names assigned to each
# category. Any values not present here fall under the "Other" tab.
SETTINGS_GROUPS = {
    "General": [
        "NAME",
        "VERSION",
        "LANG",
        "TZ",
        "HOST",
        "PORT",
        "DANGER_PORT",
        "DEBUG",
        "DEBUG_MODE",
        "MAX_WORKERS",
        "LOG_LEVEL",
        "FLASK_LOG_LEVEL",
        "CLOCK_OVERLAY",
        "CLOCK_DIGITAL",
        "CLOCK_NAVBAR",
    ],
    "Admin": [
        "USER_NAME",
        "USER_PASSWORD_HASH",
        "SECRET_KEY",
        "API_KEY",
        "SSO_TOKEN",
        "SSO_USERNAME",
        "CHATGPT_KEY",
        "SESSION_COOKIE_SECURE",
        "SESSION_COOKIE_HTTPONLY",
        "SESSION_TIMEOUT_MINUTES",
        "SKIP_LOGIN_SUBNETS",
    ],
    "Capture": [
        "DATABASE_PATH",
        "LOGGING_PATH",
        "BACKUP_PATH",
        "SCREENSHOT_DIRECTORY",
        "VIDEO_DIRECTORY",
        "SUMMARIES_DIRECTORY",
        "NUM_FRAMES",
        "CAPTURE_TIMEOUT",
        "PROBE_SIZE_DEFAULT",
        "PROBE_SIZE_RTSP",
        "PROBE_SIZE_OTHER",
        "ANALYZE_DURATION_DEFAULT",
        "ANALYZE_DURATION_RTSP",
        "ANALYZE_DURATION_OTHER",
        "LIVE_FALLBACK_FPS",
        "LIVE_MAX_FAILURES",
        "CHYRON_SPEED",
        "WATCHDOG_FAILURE_THRESHOLD",
        "WATCHDOG_RESTART_COOLDOWN",
        "WATCHDOG_MAX_FILE_HANDLES",
        "CRAWLER_STARTUP_SPREAD",
        "DISCOVERY_AUTOSTART",
        "CLIP_MODEL_NAME",
        "FFMPEG_PATH",
        "FFPROBE_PATH",
        "FFMPEG_HWACCEL",
        "FFMPEG_THREADS",
    ],
    "Advanced": [
        "EMAIL_ENABLED",
        "SMS_ENABLED",
        "CAP_ENABLED",
        "EMAIL_SENDER",
        "EMAIL_RECIPIENTS",
        "EMAIL_SMTP_SERVER",
        "EMAIL_SMTP_PORT",
        "EMAIL_USE_TLS",
        "EMAIL_USERNAME",
        "EMAIL_PASSWORD",
        "TWILIO_SID",
        "TWILIO_TOKEN",
        "TWILIO_NUMBER",
        "MCP_SERVER_COMMAND",
        "MCP_SERVER_URL",
        "CLOCK_OVERLAY",
        "CLOCK_DIGITAL",
        "CLOCK_NAVBAR",
        "CAP_ENDPOINT",
        "CAP_SENDER",
        "NOTIFY_ON_MOTION",
        "NOTIFY_ON_CAPTION",
    ],
}

# Fields that should only allow numeric values on the settings page.
NUMERIC_FIELDS = {
    "MAX_WORKERS",
    "EMAIL_SMTP_PORT",
    "LIVE_FALLBACK_FPS",
    "LIVE_MAX_FAILURES",
    "CHYRON_SPEED",
    "DANGER_PORT",
    "WATCHDOG_FAILURE_THRESHOLD",
    "WATCHDOG_RESTART_COOLDOWN",
    "WATCHDOG_MAX_FILE_HANDLES",
}

# Fields that expect email addresses.
EMAIL_FIELDS = {"EMAIL_SENDER", "EMAIL_RECIPIENTS"}

# Settings that are hidden behind the advanced toggle on the UI. Their
# corresponding form inputs are disabled unless advanced mode is enabled.
LOCKED_SETTINGS = {"CLIP_MODEL_NAME"}

# Example placeholders displayed in the settings form.
SETTINGS_PLACEHOLDERS = {
    "EMAIL_SENDER": "your-email@example.com",
    "EMAIL_RECIPIENTS": "recipient1@example.com,recipient2@example.com",
    "EMAIL_SMTP_SERVER": "smtp.example.com",
    "EMAIL_USERNAME": "your-username",
    "CAP_ENDPOINT": "https://alert.example.com",
    "CAP_SENDER": "glimpser@example.com",
}
