"""Generic landing presets with no installation-specific camera membership."""

DEFAULTS = {
    "LANDING_CONTENT_PROFILES": {
        "public": {
            "key": "public",
            "label": "Public",
            "max_scenes": 3,
            "scene_size": 2,
            "short_label": "Public",
            "lane_bias": {
                "beach": 38,
                "home": -120,
                "ops": -160,
                "retail": -90,
                "scenic": 42,
                "science": 28,
                "world": 24,
            },
            "lane_fill_order": [
                "scenic",
                "beach",
                "science",
                "world",
                "home",
                "retail",
                "ops",
            ],
            "lane_minimums": ["scenic", "beach"],
        },
        "kitchen": {
            "key": "kitchen",
            "label": "Kitchen",
            "max_scenes": 32,
            "scene_window_size": 2,
            "scene_chunk_stride": 1,
            "scene_size": 4,
            "short_label": "Kitchen",
            "lane_bias": {
                "beach": 28,
                "home": 46,
                "ops": -80,
                "plants": 16,
                "regional": 10,
                "retail": 68,
                "scenic": 18,
                "screens": 32,
                "science": 6,
                "world": -24,
            },
            "lane_fill_order": [
                "retail",
                "home",
                "screens",
                "beach",
                "plants",
                "scenic",
                "science",
                "world",
                "ops",
            ],
            "lane_minimums": ["retail", "home", "screens", "beach", "scenic"],
            "max_group_scenes": 6,
            "max_scenes_bonus": 6,
        },
        "living": {
            "key": "living",
            "label": "Living",
            "all_eligible": True,
            "rotation_ms": 15000,
            "max_rotation_ms": 30000,
            "max_scenes": 36,
            "scene_window_size": 2,
            "scene_chunk_stride": 1,
            "scene_size": 4,
            "short_label": "Living",
            "lane_bias": {
                "beach": 34,
                "home": 28,
                "ops": -96,
                "regional": 16,
                "retail": 8,
                "scenic": 34,
                "screens": 40,
                "science": 56,
                "world": 26,
            },
            "lane_fill_order": [
                "scenic",
                "beach",
                "science",
                "regional",
                "home",
                "screens",
                "world",
                "retail",
                "ops",
            ],
            "lane_minimums": ["scenic", "science", "beach", "home", "screens"],
            "max_group_scenes": 8,
            "max_scenes_bonus": 6,
        },
        "office": {
            "key": "office",
            "label": "Office",
            "all_eligible": True,
            "rotation_ms": 12000,
            "max_rotation_ms": 50000,
            "max_scenes": 56,
            "scene_window_size": 2,
            "scene_chunk_stride": 1,
            "scene_size": 6,
            "short_label": "Office",
            "lane_bias": {
                "beach": 18,
                "home": 42,
                "ops": 196,
                "plants": 50,
                "regional": 58,
                "retail": 34,
                "scenic": 12,
                "screens": 230,
                "science": 48,
                "world": 14,
            },
            "lane_fill_order": [
                "ops",
                "screens",
                "home",
                "science",
                "regional",
                "plants",
                "retail",
                "scenic",
                "world",
                "beach",
            ],
            "lane_minimums": ["ops", "screens", "home", "science", "regional"],
            "max_scenes_bonus": 16,
            "max_group_scenes": 10,
            "scene_size_bonus": 1,
        },
        "hal": {
            "key": "hal",
            "label": "Workstation",
            "max_scenes": 80,
            "scene_size": 6,
            "short_label": "Workstation",
            "lane_bias": {
                "beach": 26,
                "home": 48,
                "ops": 220,
                "plants": 72,
                "regional": 60,
                "retail": 46,
                "scenic": 28,
                "screens": 250,
                "science": 56,
                "world": 30,
            },
            "lane_fill_order": [
                "home",
                "ops",
                "screens",
                "plants",
                "retail",
                "science",
                "regional",
                "world",
                "scenic",
                "beach",
            ],
            "lane_minimums": [
                "home",
                "ops",
                "screens",
                "plants",
                "science",
                "retail",
                "regional",
                "beach",
                "scenic",
            ],
            "max_group_scenes": 10,
            "max_scenes_bonus": 36,
            "scene_chunk_stride": 1,
            "scene_window_size": 2,
        },
    },
    "LANDING_GROUP_BONUSES": {
        "regional": 30,
        "weather": 18,
        "systems": 44,
        "private": -8,
    },
    "LANDING_NAME_PENALTIES": {},
    "LANDING_LANE_HINTS": {
        "beach": [
            "beach",
            "beachhouse",
            "beach house",
            "harbor",
            "marina",
            "shore",
            "shoreline",
        ],
        "home": [
            "backyard",
            "cloner",
            "doorbell",
            "driveway",
            "front door",
            "frontdoor",
            "garage",
            "grower",
            "home",
            "plant",
        ],
        "ops": [
            "diagnostic",
            "diagnostics",
            "camerahealth",
            "capture",
            "faa",
            "health",
            "hubitat",
            "network",
            "ops",
            "radio",
            "signal",
            "status",
            "systems",
            "telemetry",
            "uplink",
        ],
        "plants": [
            "cloner",
            "grower",
            "plant",
            "plants",
            "pod",
            "purple",
            "succulent",
            "whitegrower",
        ],
        "regional": [
            "arcadia",
            "ais",
            "boatnerd",
            "canal",
            "duluth",
            "edens",
            "edgewater",
            "elmhurst",
            "freighter",
            "great lakes",
            "harbor",
            "icecover",
            "interchange",
            "kenosha",
            "lake county",
            "lake michigan",
            "lake superior",
            "lakefront",
            "locks",
            "marina",
            "marine",
            "milwaukee",
            "naval",
            "north shore",
            "northshore",
            "northwestern",
            "niu",
            "ohare",
            "pleasant prairie",
            "shipping",
            "ship",
            "soo",
            "tower",
            "vessel",
            "waukegan",
            "wilmette",
            "winthrop",
        ],
        "retail": ["jewel", "jewelry", "showroom", "store"],
        "scenic": [
            "airport",
            "beach",
            "chicago",
            "faa",
            "harbor",
            "lake",
            "river",
            "sky",
            "skyline",
            "weather",
        ],
        "screens": [
            "bandwidth",
            "camerahealth",
            "comed",
            "control panel",
            "dashboard",
            "diagnostic",
            "diagnostics",
            "eia",
            "electricity",
            "energy",
            "glimpse",
            "hubitat",
            "network",
            "old computer screen",
            "power dashboard",
            "status",
            "system",
            "systems",
            "telemetry",
        ],
        "science": [
            "argonne",
            "aurora",
            "flare",
            "goes",
            "noaa",
            "science",
            "solar",
            "space",
            "sun",
            "swpc",
        ],
        "world": ["breaking", "global", "news", "radar", "satellite", "storm", "world"],
    },
    "LANDING_HOST_PROFILE_HINTS": [],
    "LANDING_HOST_MODE_HINTS": [],
    "LANDING_PRIORITY_CAMERAS": [],
    "LANDING_PROFILE_EXCLUDED_CAMERAS": {},
    "LANDING_LOCAL_HINTS": ["192.168.", "regional", "plants", "store"],
    "LANDING_DWELL_GROUPS": [],
    "LANDING_STATUS_PREFIXES": ["hubitat"],
    "LANDING_STATUS_CAMERAS": [],
}
