name: Docker Build

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Docker image
        run: docker build -t glimpser .
