# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  schedule:
    - cron: '43 2 * * 4'
  push:
    branches: [ "main" ]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure the latest Node.js version is used

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action@v1.7.1
        with:
          scan-args: |-
            -r
            --skip-git
            ./

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure the latest Node.js version is used

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action@v1.7.1
        with:
          scan-args: |-
            -r
            --skip-git
            ./

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
